// Generated by scripts/generate-base-sepolia-test-gallery-manifest.ts.
// UniversalPoolArtMarketplace deployment facts only. No live validation.

// prettier-ignore
export const BASE_SEPOLIA_TEST_GALLERY_MANIFEST = {
  "schemaVersion": 2,
  "chainId": 84532,
  "addresses": {
    "fame": "0x2cF0408Ee86b337216dD0073ab257F84497067cA",
    "mirror": "0x2907936013BDF568F98A98893AC1C746256A9cC5",
    "creatorMagic": "0xa16C005203cD46cC1929cc8e494cF7945887951B",
    "gallery": "0x821ab043a94688aC22C5a1b0113fc33ed4Fb6843"
  },
  "testToken": {
    "name": "Example",
    "symbol": "TEST",
    "unit": "1000000"
  },
  "collection": {
    "firstTokenId": 1,
    "lastTokenId": 888
  },
  "deployment": {
    "blockNumber": 44329992
  },
  "metadataStrategy": "nested-onchain-data-uri",
  "explorerBaseUrl": "https://sepolia.basescan.org"
} as const;

export type BaseSepoliaTestGalleryManifest =
  typeof BASE_SEPOLIA_TEST_GALLERY_MANIFEST;
