sources:
  - name: fls-sepolia
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/67995/fls-sepolia/version/latest
    transforms:
      - prefix:
          value: sepolia_
          includeRootOperations: true
          includeTypes: false
  - name: fls-mainnet
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/67995/fls/version/latest
  - name: fame-nft-base
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/67995/fame-nft-base/v0.0.4
    transforms:
      - prefix:
          value: base_fame_nft_
          includeRootOperations: true
          includeTypes: false
documents:
  - ./src/**/*.graphql
