export const fameRouterAbi = [
  {
    type: "function",
    name: "executeRoute",
    stateMutability: "payable",
    inputs: [
      {
        name: "route",
        type: "tuple",
        components: [
          { name: "version", type: "uint16" },
          { name: "tokenIn", type: "address" },
          { name: "tokenOut", type: "address" },
          { name: "amountIn", type: "uint256" },
          { name: "minAmountOutAfterFee", type: "uint256" },
          { name: "recipient", type: "address" },
          { name: "deadline", type: "uint256" },
          {
            name: "legs",
            type: "tuple[]",
            components: [
              { name: "tokenIn", type: "address" },
              { name: "tokenOut", type: "address" },
              { name: "venue", type: "uint8" },
              { name: "amountMode", type: "uint8" },
              { name: "amount", type: "uint256" },
              { name: "minAmountOut", type: "uint256" },
              { name: "target", type: "address" },
              { name: "data", type: "bytes" },
            ],
          },
        ],
      },
    ],
    outputs: [{ name: "netAmountOut", type: "uint256" }],
  },
  {
    type: "function",
    name: "hashRoute",
    stateMutability: "pure",
    inputs: [
      {
        name: "route",
        type: "tuple",
        components: [
          { name: "version", type: "uint16" },
          { name: "tokenIn", type: "address" },
          { name: "tokenOut", type: "address" },
          { name: "amountIn", type: "uint256" },
          { name: "minAmountOutAfterFee", type: "uint256" },
          { name: "recipient", type: "address" },
          { name: "deadline", type: "uint256" },
          {
            name: "legs",
            type: "tuple[]",
            components: [
              { name: "tokenIn", type: "address" },
              { name: "tokenOut", type: "address" },
              { name: "venue", type: "uint8" },
              { name: "amountMode", type: "uint8" },
              { name: "amount", type: "uint256" },
              { name: "minAmountOut", type: "uint256" },
              { name: "target", type: "address" },
              { name: "data", type: "bytes" },
            ],
          },
        ],
      },
    ],
    outputs: [{ type: "bytes32" }],
  },
  {
    type: "function",
    name: "feePpm",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint32" }],
  },
  {
    type: "function",
    name: "venueFamilyEnabled",
    stateMutability: "view",
    inputs: [{ type: "uint8" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "venueTargetEnabled",
    stateMutability: "view",
    inputs: [{ type: "uint8" }, { type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "v4HookDataHashEnabled",
    stateMutability: "view",
    inputs: [{ type: "bytes32" }],
    outputs: [{ type: "bool" }],
  },
] as const;
