import { spawn, type ChildProcess } from "node:child_process";
import {
  existsSync,
  readFileSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import type { Readable } from "node:stream";

const ENV_LOCAL_PATH = ".env.local";
const writeEnvLocal =
  process.argv.includes("--write-env-local") ||
  process.env.FAME_SWAP_WRITE_ENV_LOCAL === "1";
const wslMode =
  process.argv.includes("--wsl") || process.argv.includes("--windows-host");

function argValue(name: string): string | null {
  const index = process.argv.indexOf(name);
  if (index >= 0) return process.argv[index + 1] ?? null;

  const prefix = `${name}=`;
  const match = process.argv.find((arg) => arg.startsWith(prefix));
  return match ? match.slice(prefix.length) : null;
}

const anvilBindHostArg =
  argValue("--anvil-bind-host") ??
  argValue("--bind-host") ??
  argValue("--host");
const anvilPublicHostArg =
  argValue("--anvil-public-host") ?? argValue("--public-host");

const fallbackRpcJsonEnv = [
  "NEXT_PUBLIC_SEPOLIA_RPC_JSON",
  "NEXT_PUBLIC_BASE_SEPOLIA_RPC_JSON",
  "NEXT_PUBLIC_POLYGON_AMOY_RPCS_JSON",
] as const;

const fallbackRpcUrlEnv = [
  "NEXT_PUBLIC_MAINNET_RPC_URL_1",
  "NEXT_PUBLIC_POLYGON_RPC_URL_1",
  "NEXT_PUBLIC_POLYGON_RPC_URL_2",
] as const;

let forkRpcUrl: string | null = null;
let routerAddress: string | null = null;
let slippageBps = process.env.NEXT_PUBLIC_FAME_SWAP_SLIPPAGE_BPS ?? "100";
let wroteEnvLocal = false;
let shuttingDown = false;

const originalEnvLocal = existsSync(ENV_LOCAL_PATH)
  ? readFileSync(ENV_LOCAL_PATH, "utf8")
  : null;

function stopChild(child: ChildProcess): void {
  if (child.exitCode !== null || child.signalCode !== null) return;
  child.kill("SIGTERM");
}

function restoreEnvLocal(): void {
  if (!wroteEnvLocal) return;

  if (originalEnvLocal === null) {
    try {
      unlinkSync(ENV_LOCAL_PATH);
    } catch {
      // It may already be gone if removed manually.
    }
    return;
  }

  writeFileSync(ENV_LOCAL_PATH, originalEnvLocal);
}

function shutdown(child: ChildProcess, exitCode = 0): void {
  if (shuttingDown) return;
  shuttingDown = true;
  stopChild(child);
  restoreEnvLocal();
  process.exitCode = exitCode;
}

function envLines(): string[] {
  if (!forkRpcUrl || !routerAddress) {
    throw new Error("Fork RPC URL and router address are required.");
  }

  const values: Record<string, string> = {
    NEXT_PUBLIC_BASE_RPC_URL_1: forkRpcUrl,
    NEXT_PUBLIC_FAME_ROUTER_ADDRESS: routerAddress,
    NEXT_PUBLIC_FAME_SWAP_SLIPPAGE_BPS: slippageBps,
  };

  for (const name of fallbackRpcJsonEnv) {
    values[name] = process.env[name] ?? JSON.stringify([forkRpcUrl]);
  }

  for (const name of fallbackRpcUrlEnv) {
    values[name] = process.env[name] ?? forkRpcUrl;
  }

  return Object.entries(values).map(
    ([name, value]) => `${name}=${JSON.stringify(value)}`,
  );
}

function maybeWriteEnvLocal(): void {
  if (!writeEnvLocal || wroteEnvLocal || !forkRpcUrl || !routerAddress) return;

  writeFileSync(
    ENV_LOCAL_PATH,
    [
      "# Generated by bun run fame-swap:fork -- --write-env-local",
      "# This file is restored or removed when the fork script exits cleanly.",
      ...envLines(),
      "",
    ].join("\n"),
  );
  wroteEnvLocal = true;
  console.log(`Wrote ${ENV_LOCAL_PATH} for the local FAME router fork.`);
}

function handleLine(line: string): void {
  if (line.startsWith("NEXT_PUBLIC_BASE_RPC_URL_1=")) {
    forkRpcUrl = line.slice("NEXT_PUBLIC_BASE_RPC_URL_1=".length).trim();
    maybeWriteEnvLocal();
    return;
  }

  if (line.startsWith("NEXT_PUBLIC_FAME_ROUTER_ADDRESS=")) {
    routerAddress = line
      .slice("NEXT_PUBLIC_FAME_ROUTER_ADDRESS=".length)
      .trim();
    maybeWriteEnvLocal();
    return;
  }

  if (line.startsWith("NEXT_PUBLIC_FAME_SWAP_SLIPPAGE_BPS=")) {
    slippageBps = line
      .slice("NEXT_PUBLIC_FAME_SWAP_SLIPPAGE_BPS=".length)
      .trim();
    maybeWriteEnvLocal();
  }
}

function pipeLines(stream: Readable, write: (chunk: string) => void): void {
  let buffer = "";

  stream.on("data", (chunk: Buffer | string) => {
    const text = chunk.toString();
    write(text);
    buffer += text;

    const lines = buffer.split(/\r?\n/);
    buffer = lines.pop() ?? "";
    for (const line of lines) {
      handleLine(line);
    }
  });

  stream.on("end", () => {
    if (buffer.length > 0) {
      handleLine(buffer);
    }
  });
}

function forkSmokeEnv(): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = {
    ...process.env,
    FAME_SWAP_ALLOW_RPC_URL_PROCESS_ARG:
      process.env.FAME_SWAP_ALLOW_RPC_URL_PROCESS_ARG ?? "1",
    FAME_SWAP_FORK_BLOCK: process.env.FAME_SWAP_FORK_BLOCK ?? "latest",
    FAME_SWAP_KEEP_FORK_ALIVE: "1",
    FAME_SWAP_SKIP_ROUTE_SMOKE: "1",
  };

  if (wslMode && !env.FAME_SWAP_ANVIL_BIND_HOST) {
    env.FAME_SWAP_ANVIL_BIND_HOST = "0.0.0.0";
  }
  if (anvilBindHostArg) {
    env.FAME_SWAP_ANVIL_BIND_HOST = anvilBindHostArg;
  }
  if (anvilPublicHostArg) {
    env.FAME_SWAP_ANVIL_PUBLIC_HOST = anvilPublicHostArg;
  }

  if (process.env.FAME_SWAP_USE_CONFIGURED_ROUTER !== "1") {
    env.FAME_SWAP_IGNORE_CONFIGURED_ROUTER = "1";
    delete env.NEXT_PUBLIC_FAME_ROUTER_ADDRESS;
    delete env.FAME_ROUTER_ADDRESS;
  }

  return env;
}

function main(): void {
  const fork = spawn("bun", ["run", "fame-swap:fork-smoke"], {
    env: forkSmokeEnv(),
    stdio: ["inherit", "pipe", "pipe"],
  });

  pipeLines(fork.stdout, process.stdout.write.bind(process.stdout));
  pipeLines(fork.stderr, process.stderr.write.bind(process.stderr));

  fork.on("exit", (code) => {
    if (!shuttingDown) {
      restoreEnvLocal();
      process.exitCode = code ?? 1;
    }
  });

  process.once("SIGINT", () => {
    shutdown(fork, 130);
  });
  process.once("SIGTERM", () => {
    shutdown(fork, 143);
  });
}

main();
