import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";
import {
  existsSync,
  readFileSync,
  rmSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import type { Readable } from "node:stream";

const ENV_LOCAL_PATH = ".env.local";
const NEXT_BUILD_DIR = ".next";
const fallbackRpcJsonEnv = [
  "NEXT_PUBLIC_SEPOLIA_RPC_JSON",
  "NEXT_PUBLIC_BASE_SEPOLIA_RPC_JSON",
  "NEXT_PUBLIC_POLYGON_AMOY_RPCS_JSON",
] as const;

const fallbackRpcUrlEnv = [
  "NEXT_PUBLIC_MAINNET_RPC_URL_1",
  "NEXT_PUBLIC_POLYGON_RPC_URL_1",
  "NEXT_PUBLIC_POLYGON_RPC_URL_2",
] as const;

let forkRpcUrl: string | null = null;
let routerAddress: string | null = null;
let slippageBps = process.env.NEXT_PUBLIC_FAME_SWAP_SLIPPAGE_BPS ?? "100";
let dev: ChildProcessWithoutNullStreams | null = null;
let shuttingDown = false;
const originalEnvLocal = existsSync(ENV_LOCAL_PATH)
  ? readFileSync(ENV_LOCAL_PATH, "utf8")
  : null;
let wroteEnvLocal = false;
const wslMode =
  process.argv.includes("--wsl") || process.argv.includes("--windows-host");

function argValue(name: string): string | null {
  const index = process.argv.indexOf(name);
  if (index >= 0) return process.argv[index + 1] ?? null;

  const prefix = `${name}=`;
  const match = process.argv.find((arg) => arg.startsWith(prefix));
  return match ? match.slice(prefix.length) : null;
}

const anvilBindHostArg =
  argValue("--anvil-bind-host") ??
  argValue("--bind-host") ??
  argValue("--host");
const anvilPublicHostArg =
  argValue("--anvil-public-host") ?? argValue("--public-host");

function startChild(
  command: string,
  args: string[],
  env: NodeJS.ProcessEnv,
): ChildProcessWithoutNullStreams {
  return spawn(command, args, {
    env,
    stdio: ["inherit", "pipe", "pipe"],
  });
}

function stopChild(child: ChildProcessWithoutNullStreams | null): void {
  if (!child || child.exitCode !== null || child.signalCode !== null) return;
  child.kill("SIGTERM");
}

function restoreEnvLocal(): void {
  if (!wroteEnvLocal) return;

  if (originalEnvLocal === null) {
    try {
      unlinkSync(ENV_LOCAL_PATH);
    } catch {
      // The file may already be gone if the developer removed it manually.
    }
    return;
  }

  writeFileSync(ENV_LOCAL_PATH, originalEnvLocal);
}

function shutdown(
  fork: ChildProcessWithoutNullStreams,
  exitCode = 0,
): void {
  if (shuttingDown) return;
  shuttingDown = true;
  stopChild(dev);
  stopChild(fork);
  restoreEnvLocal();
  process.exitCode = exitCode;
}

function localDevEnv(): NodeJS.ProcessEnv {
  if (!forkRpcUrl || !routerAddress) {
    throw new Error("Fork RPC URL and router address are required.");
  }

  const env: NodeJS.ProcessEnv = {
    ...process.env,
    NEXT_PUBLIC_BASE_RPC_URL_1: forkRpcUrl,
    NEXT_PUBLIC_FAME_ROUTER_ADDRESS: routerAddress,
    NEXT_PUBLIC_FAME_SWAP_SLIPPAGE_BPS: slippageBps,
  };

  for (const name of fallbackRpcJsonEnv) {
    env[name] = env[name] ?? JSON.stringify([forkRpcUrl]);
  }

  for (const name of fallbackRpcUrlEnv) {
    env[name] = env[name] ?? forkRpcUrl;
  }

  return env;
}

function writeNextEnvLocal(env: NodeJS.ProcessEnv): void {
  const names = [
    "NEXT_PUBLIC_BASE_RPC_URL_1",
    "NEXT_PUBLIC_FAME_ROUTER_ADDRESS",
    "NEXT_PUBLIC_FAME_SWAP_SLIPPAGE_BPS",
    ...fallbackRpcJsonEnv,
    ...fallbackRpcUrlEnv,
  ] as const;
  const generated = [
    "# Generated by bun run fame-swap:local-dev",
    "# This file is restored or removed when the script exits cleanly.",
    ...names.map((name) => `${name}=${JSON.stringify(env[name] ?? "")}`),
    "",
  ].join("\n");

  writeFileSync(ENV_LOCAL_PATH, generated);
  wroteEnvLocal = true;
}

function cleanNextCache(): void {
  if (process.env.FAME_SWAP_KEEP_NEXT_CACHE === "1") return;
  rmSync(NEXT_BUILD_DIR, { recursive: true, force: true });
}

function maybeStartDev(fork: ChildProcessWithoutNullStreams): void {
  if (dev || !forkRpcUrl || !routerAddress) return;
  const env = localDevEnv();

  console.log("");
  console.log("Starting www dev server against local FAME router fork.");
  console.log(`NEXT_PUBLIC_BASE_RPC_URL_1=${forkRpcUrl}`);
  console.log(`NEXT_PUBLIC_FAME_ROUTER_ADDRESS=${routerAddress}`);
  console.log("");

  writeNextEnvLocal(env);
  cleanNextCache();
  dev = startChild("yarn", ["dev"], env);
  dev.stdout.pipe(process.stdout);
  dev.stderr.pipe(process.stderr);
  dev.on("exit", (code) => {
    shutdown(fork, code ?? 1);
  });
}

function handleLine(line: string, fork: ChildProcessWithoutNullStreams): void {
  if (line.startsWith("NEXT_PUBLIC_BASE_RPC_URL_1=")) {
    forkRpcUrl = line.slice("NEXT_PUBLIC_BASE_RPC_URL_1=".length).trim();
    maybeStartDev(fork);
    return;
  }

  if (line.startsWith("NEXT_PUBLIC_FAME_ROUTER_ADDRESS=")) {
    routerAddress = line
      .slice("NEXT_PUBLIC_FAME_ROUTER_ADDRESS=".length)
      .trim();
    maybeStartDev(fork);
    return;
  }

  if (line.startsWith("NEXT_PUBLIC_FAME_SWAP_SLIPPAGE_BPS=")) {
    slippageBps = line
      .slice("NEXT_PUBLIC_FAME_SWAP_SLIPPAGE_BPS=".length)
      .trim();
  }
}

function pipeLines(
  stream: Readable,
  write: (chunk: string) => void,
  onLine: (line: string) => void,
): void {
  let buffer = "";

  stream.on("data", (chunk: Buffer | string) => {
    const text = chunk.toString();
    write(text);
    buffer += text;

    const lines = buffer.split(/\r?\n/);
    buffer = lines.pop() ?? "";
    for (const line of lines) {
      onLine(line);
    }
  });

  stream.on("end", () => {
    if (buffer.length > 0) {
      onLine(buffer);
    }
  });
}

function forkSmokeEnv(): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = {
    ...process.env,
    FAME_SWAP_ALLOW_RPC_URL_PROCESS_ARG:
      process.env.FAME_SWAP_ALLOW_RPC_URL_PROCESS_ARG ?? "1",
    FAME_SWAP_FORK_BLOCK: process.env.FAME_SWAP_FORK_BLOCK ?? "latest",
    FAME_SWAP_KEEP_FORK_ALIVE: "1",
  };

  if (wslMode && !env.FAME_SWAP_ANVIL_BIND_HOST) {
    env.FAME_SWAP_ANVIL_BIND_HOST = "0.0.0.0";
  }
  if (anvilBindHostArg) {
    env.FAME_SWAP_ANVIL_BIND_HOST = anvilBindHostArg;
  }
  if (anvilPublicHostArg) {
    env.FAME_SWAP_ANVIL_PUBLIC_HOST = anvilPublicHostArg;
  }

  if (process.env.FAME_SWAP_USE_CONFIGURED_ROUTER !== "1") {
    env.FAME_SWAP_IGNORE_CONFIGURED_ROUTER = "1";
    delete env.NEXT_PUBLIC_FAME_ROUTER_ADDRESS;
    delete env.FAME_ROUTER_ADDRESS;
  }

  return env;
}

function main(): void {
  const fork = startChild(
    "bun",
    ["run", "fame-swap:fork-smoke"],
    forkSmokeEnv(),
  );

  pipeLines(fork.stdout, process.stdout.write.bind(process.stdout), (line) =>
    handleLine(line, fork),
  );
  pipeLines(fork.stderr, process.stderr.write.bind(process.stderr), (line) =>
    handleLine(line, fork),
  );

  fork.on("exit", (code) => {
    if (!shuttingDown && !dev) {
      process.exitCode = code ?? 1;
    }
  });

  process.once("SIGINT", () => {
    shutdown(fork, 130);
  });
  process.once("SIGTERM", () => {
    shutdown(fork, 143);
  });
}

main();
