import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const GENERATED_PATH = resolve(
  process.cwd(),
  "src/features/fame-market/config/baseSepoliaTestGallery.generated.ts",
);

export function buildBaseSepoliaTestGalleryManifest() {
  return {
    schemaVersion: 2,
    chainId: 84_532,
    addresses: {
      fame: "0x2cF0408Ee86b337216dD0073ab257F84497067cA",
      mirror: "0x2907936013BDF568F98A98893AC1C746256A9cC5",
      creatorMagic: "0xa16C005203cD46cC1929cc8e494cF7945887951B",
      gallery: "0x821ab043a94688aC22C5a1b0113fc33ed4Fb6843",
    },
    testToken: {
      name: "Example",
      symbol: "TEST",
      unit: "1000000",
    },
    collection: {
      firstTokenId: 1,
      lastTokenId: 888,
    },
    deployment: {
      blockNumber: 44_329_992,
    },
    metadataStrategy: "nested-onchain-data-uri",
    explorerBaseUrl: "https://sepolia.basescan.org",
  } as const;
}

export type BaseSepoliaTestGalleryManifest = ReturnType<
  typeof buildBaseSepoliaTestGalleryManifest
>;

export function formatGeneratedManifest(
  manifest: BaseSepoliaTestGalleryManifest,
): string {
  return `// Generated by scripts/generate-base-sepolia-test-gallery-manifest.ts.
// UniversalPoolArtMarketplace deployment facts only. No live validation.

// prettier-ignore
export const BASE_SEPOLIA_TEST_GALLERY_MANIFEST = ${JSON.stringify(
    manifest,
    null,
    2,
  )} as const;

export type BaseSepoliaTestGalleryManifest =
  typeof BASE_SEPOLIA_TEST_GALLERY_MANIFEST;
`;
}

export async function generateBaseSepoliaTestGalleryManifest(options?: {
  check?: boolean;
}) {
  const manifest = buildBaseSepoliaTestGalleryManifest();
  const generated = formatGeneratedManifest(manifest);

  if (options?.check) {
    const committed = await readFile(GENERATED_PATH, "utf8");
    if (committed !== generated) {
      throw new Error(
        "Committed Base Sepolia TEST gallery manifest is not reproducible",
      );
    }
    return manifest;
  }

  await writeFile(GENERATED_PATH, generated);
  return manifest;
}

function shouldRunCli() {
  return (
    process.argv[1]?.endsWith(
      "generate-base-sepolia-test-gallery-manifest.ts",
    ) ?? false
  );
}

if (shouldRunCli()) {
  const check = process.argv.includes("--check");
  await generateBaseSepoliaTestGalleryManifest({ check });
  process.stdout.write(
    check
      ? "Base Sepolia TEST gallery manifest is reproducible.\n"
      : `Generated ${GENERATED_PATH}\n`,
  );
}
