name: Deploy to Vercel Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: tspascoal/get-user-teams-membership@v3
        id: isOrgMember
        with:
          username: ${{ github.actor }}
          team: www-deployers
          GITHUB_TOKEN: ${{ secrets.ORG_READ_ACCESS_GITHUB_TOKEN }}
      - name: Checkout code
        if: ${{ steps.isOrgMember.outputs.isTeamMember == 'true' }}
        uses: actions/checkout@v3

      - name: Setup Node.js
        if: ${{ steps.isOrgMember.outputs.isTeamMember == 'true' }}
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        if: ${{ steps.isOrgMember.outputs.isTeamMember == 'true' }}
        run: yarn

      # - name: Authenticate with Vercel
      #   if: ${{ steps.isOrgMember.outputs.isTeamMember == 'true' }}
      #   env:
      #     VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      #   run: vercel login --token $VERCEL_TOKEN

      - name: Deploy to Vercel
        if: ${{ steps.isOrgMember.outputs.isTeamMember == 'true' }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: vercel --token $VERCEL_TOKEN  > deployment.txt
        cat deployment.txt
        continue-on-error: false
      - name: Extract Vercel URL
        id: extract-url
        run: |
          DEPLOYMENT_URL=$(grep -o 'https://.*\.vercel\.app' deployment.txt)
          echo "Deployment URL: $DEPLOYMENT_URL"
          echo "VERCEL_URL=$DEPLOYMENT_URL" >> $GITHUB_ENV
      - name: Comment on PR with Vercel deployment URL
        if: always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Vercel Deployment Preview:
            ${{ env.VERCEL_URL }}