// Generated by scripts/generate-base-sepolia-test-gallery-manifest.ts.
// Source checkpoint: Base Sepolia block 44267553
// Source block hash: 0x59e6365e9843a3a4be266430f94a7a28ec39b3e103473d91db2c29d814a372cd

// prettier-ignore
export const BASE_SEPOLIA_TEST_GALLERY_MANIFEST = {
  "schemaVersion": 1,
  "generatorVersion": 1,
  "chainId": 84532,
  "addresses": {
    "fame": "0x2cF0408Ee86b337216dD0073ab257F84497067cA",
    "mirror": "0x2907936013BDF568F98A98893AC1C746256A9cC5",
    "renderer": "0x980f1c21b29d4e16ac3Fc49Fe9Aaf64b97C5A9De",
    "creatorMagic": "0xa16C005203cD46cC1929cc8e494cF7945887951B",
    "gallery": "0x7f9bA27F40686E548f613e679835158070901c47",
    "admin": "0xD52E2A6bBcEba9673440e4D7843Db6713E9B6FD9",
    "feeRecipient": "0xD52E2A6bBcEba9673440e4D7843Db6713E9B6FD9",
    "smokeRecipient": "0x7307E109C747AaD76CBc0A09612b8350410D35ba"
  },
  "testToken": {
    "name": "Example",
    "symbol": "TEST",
    "unit": "1000000"
  },
  "collection": {
    "firstTokenId": 1,
    "lastTokenId": 888
  },
  "deployment": {
    "blockNumber": 44267510,
    "blockHash": "0x1c7b8ca7765a7bdec064b0d63b662a26ccd568f4d58804135854ae120a0228ad"
  },
  "checkpoint": {
    "blockNumber": 44267553,
    "blockHash": "0x59e6365e9843a3a4be266430f94a7a28ec39b3e103473d91db2c29d814a372cd",
    "candidateTokenIds": [
      1
    ]
  }
} as const;

export type BaseSepoliaTestGalleryManifest =
  typeof BASE_SEPOLIA_TEST_GALLERY_MANIFEST;
